//Sala 1

Integrantes [
"Victor Samuel Ararat Castro",
"Alex Vinicio Albán Cedeño",
"JEFFERSON JAIME FARIAS HERNANDEZ",
"MEISY LISBETH CHOMPOL HOLGUIN",
"RAUL FERNANDO TRUJILLO VERA",
"LUIS ENRIQUE ALVAREZ MEJIA",
"MIRELLA ANTONIA CRISTOBA MEDINA",
"MARK ANTHONY SANCHEZ GOMEZ",
"OSCAR ADRIAN JIMENEZ COX",
""
]
